In [3]:
import numpy as np
print(np.__version__)

2.5.1


In [4]:
array = np.array([1, 2, 3, 4])
array *= 2
print(array)

[2 4 6 8]


In [5]:
# MULTIDIMENSIONAL ARRAYS
array = np.array("A")
print(array.ndim)
print(array.shape)


array = np.array(["A", "B", "C"])
print(array.ndim)
print(array.shape)

array = np.array([["A", "B", "C"],
                 ["A", "B", "C"],
                 ["A", "B", "C"]])
print(array.ndim)
print(array.shape)

array = np.array([[["A", "B", "C"], ["D", "E", "F"], ["G", "H", "I"]],
                  [["J", "K", "L"], ["M", "N", "O"], ["P", "Q", "R"]],
                  [["S", "T", "U"], ["V", "W", "X"], ["Y", "Z", "-"]]])
print(array.ndim)
print(array.shape)

# [LAYER, ROW, COLUMN]
print(array[2, 2, 2])

word = array[1, 1, 0] + array[0, 2, 2] + array[1, 2, 2] + array[0, 0, 0] + array[1, 1, 1] + array[0, 1, 0] + array[0, 0, 0]
print(word)

0
()
1
(3,)
2
(3, 3)
3
(3, 3, 3)
-
MIRANDA


In [6]:
# SLICING
array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

# array[start:end:step]
# array[row, column]
print(array[::2, ::-2])

[[ 4  2]
 [12 10]]


In [7]:
# SCALAR ARITHMETIC
array = np.array([1,3,5])
array *= 2
print(array)

# VECTORIZED MATH FUNCTIONS
array = np.sqrt(array)
print(array)
print(np.round(array))

# ELEMENT-WISE ARITHMETIC
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = array1 ** array2
print(array3)

# COMPARISON OPERATORS
scores = np.array([50, 75, 100])
passed = scores >= 60
print(passed)
scores[scores < 60] = 0
print(scores)

[ 2  6 10]
[1.41421356 2.44948974 3.16227766]
[1. 2. 3.]
[  1  32 729]
[False  True  True]
[  0  75 100]


In [18]:
# BROADCASTING
array1 = np.array([[1,2,3,4]])
array2 = np.array([[1],
                   [2],
                   [3],
                   [4]])

print(array1.shape)
print(array2.shape)

# *All Dimensions must match or contain a 1*
print(array1 * array2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [26]:
# AGGREGATE FUNCTIONS
array = np.array([[1, 2, 3, 4, 5]])
print(np.mean(array, axis=1))

[3.]


In [42]:
# FILTERING
array = np.array([[15, 18, 99],
                 [56, 87, 8]])

teenagers = array[array < 18]
adults = array[(array >= 18) & (array < 65)]
seniors = array[(array >= 65)]
evens = array[(array & 2 == 0)]

print(teenagers)
print(adults)
print(seniors)
print(evens)

adults = np.where(array >= 18, array, np.nan)
print(adults)

[15  8]
[18 56]
[99 87]
[56  8]
[[nan 18. 99.]
 [56. 87. nan]]


In [57]:
# RANDOM NUMBERS
rng = np.random.default_rng()
random_ints = rng.integers(low=1, high=11, size=5)
print(random_ints)

# FLOATS
random_floats = np.random.uniform(low=1, high=11, size=5)
print(random_floats)

[ 8  8 10  3  7]
[ 5.92301257  6.84262202  4.12149126 10.43445175  4.89772199]
