In [16]:
import torch

print("PyTorch Version:", torch.__version__)
print("Is CUDA available?", torch.cuda.is_available())

PyTorch Version: 2.13.0+cu126
Is CUDA available? True


In [17]:
# scalar
scalar = torch.tensor(7)
print(scalar.ndim)

# get tensor back as a python int
print(scalar.item())

0
7


In [18]:
# vector
vector = torch.tensor([7, 1])
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [19]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [20]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0, 1, 2])

3
torch.Size([1, 3, 3])
tensor(6)


In [21]:
# generate random tensor
random_tensor = torch.rand(2, 3)
print(random_tensor)

random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channel, height, width

tensor([[0.6525, 0.0155, 0.8312],
        [0.5615, 0.5623, 0.5232]])


In [22]:
# zeroes & ones
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))

In [23]:
# creating a range of tensors
one_to_ten = torch.arange(1, 11, step=1)
print(one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [24]:
# creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [25]:
# float32 tensor
float_32_tensor = torch.tensor([3, 6, 9],
                               dtype=None, # what datatype the tensor is (default: float32
                               device=None, # what device the tensor is on (default: cpu)
                               requires_grad=False # whether or not to track gradients with this tensor's operation
                               )

In [26]:
# float16 tensor
float_16_tensor = float_32_tensor.type(torch.half)
print(float_16_tensor * float_32_tensor)

tensor([ 9., 36., 81.], dtype=torch.float16)


In [27]:
# manipulating tensors (+ - * / %)
tensor1 = torch.tensor([1,2,3])

tensor_add = tensor1 + 10
print(tensor_add)

tensor_multiply = tensor1 * 10
print(tensor_multiply)

tensor([11, 12, 13])
tensor([10, 20, 30])


In [31]:
# element wise multiplication
tensor2 = torch.tensor([4,5,6])
print(f"{tensor1} * {tensor2} = {tensor1 * tensor2}")

# matrix multiplication
print(torch.matmul(tensor1, tensor2))

tensor([1, 2, 3]) * tensor([4, 5, 6]) = tensor([ 4, 10, 18])
tensor(32)
