In [28]:
import torch
import numpy as np

print("PyTorch Version:", torch.__version__)
print("Is CUDA available?", torch.cuda.is_available())

PyTorch Version: 2.13.0+cu126
Is CUDA available? True


In [29]:
# scalar
scalar = torch.tensor(7)
print(scalar.ndim)

# get tensor back as a python int
print(scalar.item())

0
7


In [30]:
# vector
vector = torch.tensor([7, 1])
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [31]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [32]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0, 1, 2])

3
torch.Size([1, 3, 3])
tensor(6)


In [33]:
# generate random tensor
random_tensor = torch.rand(2, 3)
print(random_tensor)

random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channel, height, width

tensor([[0.9456, 0.3906, 0.4655],
        [0.3700, 0.7737, 0.8485]])


In [34]:
# zeroes & ones
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))

In [35]:
# creating a range of tensors
one_to_ten = torch.arange(1, 11, step=1)
print(one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [36]:
# creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [37]:
# float32 tensor
float_32_tensor = torch.tensor([3, 6, 9],
                               dtype=None, # what datatype the tensor is (default: float32
                               device=None, # what device the tensor is on (default: cpu)
                               requires_grad=False # whether or not to track gradients with this tensor's operation
                               )

In [38]:
# float16 tensor
float_16_tensor = float_32_tensor.type(torch.half)
print(float_16_tensor * float_32_tensor)

tensor([ 9., 36., 81.], dtype=torch.float16)


In [39]:
# manipulating tensors (+ - * / %)
tensor1 = torch.tensor([1,2,3])

tensor_add = tensor1 + 10
print(tensor_add)

tensor_multiply = tensor1 * 10
print(tensor_multiply)

tensor([11, 12, 13])
tensor([10, 20, 30])


In [40]:
# element wise multiplication
tensor2 = torch.tensor([4,5,6])
print(f"{tensor1} * {tensor2} = {tensor1 * tensor2}")

# matrix multiplication
print(torch.matmul(tensor1, tensor2))

tensor([1, 2, 3]) * tensor([4, 5, 6]) = tensor([ 4, 10, 18])
tensor(32)


In [41]:
# tensor transposition
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])  # Shape: (3, 2)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])  # Shape: (3, 2)

# torch.matmul(tensor_A, tensor_B) -> Triggers RuntimeError: shape mismatch

# Solution: Transpose tensor_B to shape (2, 3)
output = torch.matmul(tensor_A, tensor_B.T)
print(f"Output shape: {output.shape}\nOutput:\n{output}")
# Output shape: torch.Size([3, 3])

Output shape: torch.Size([3, 3])
Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [49]:
# tensor aggregation
x = torch.arange(0, 100, 10)  # tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

# Find Min, Max, Sum
print(f"Min: {x.min()}")
print(f"Max: {x.max()}")
print(f"Sum: {x.sum()}")

# Find Mean (Requires floating point or complex datatype)
# torch.mean(x) will fail if x is torch.int64
print(f"Mean: {x.type(torch.float32).mean()}")

# Positional Min/Max (Argmin / Argmax)
# Returns the index where the minimum or maximum value occurs
print(f"Index of Min: {x.argmin()}")  # Output: 0
print(f"Index of Max: {x.argmax()}")  # Output: 9

tensor([[[0.3362, 0.0014, 0.5479],
         [0.7168, 0.6899, 0.6658],
         [0.1161, 0.0916, 0.7475]],

        [[0.1627, 0.7143, 0.2953],
         [0.9981, 0.7003, 0.1567],
         [0.2912, 0.3650, 0.9677]],

        [[0.6141, 0.4134, 0.0809],
         [0.9770, 0.3865, 0.7902],
         [0.4791, 0.4119, 0.8858]]])
tensor(0.0809)


In [ ]:
# reshaping, stacking, squeezing, permuting
x = torch.arange(1., 10.)  # Shape: (9,)

# 1. Reshape
x_reshaped = x.reshape(1, 9)
print(f"Reshaped: {x_reshaped.shape}")  # torch.Size([1, 9])

# 2. View (Shares memory with original tensor)
z = x.view(1, 9)
z[:, 0] = 5  # Modifying z also modifies x!
print(f"Original x after modifying view z: {x[0]}")  # Output: 5.0

# 3. Stack
x_stacked = torch.stack([x, x, x], dim=0)
print(f"Stacked shape (dim=0): {x_stacked.shape}")  # torch.Size([3, 9])

# 4. Squeeze & Unsqueeze
x_single = torch.zeros(1, 1, 5)
x_squeezed = x_single.squeeze()
print(f"Squeezed shape: {x_squeezed.shape}")  # torch.Size([5])

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"Unsqueezed shape: {x_unsqueezed.shape}")  # torch.Size([1, 5])

# 5. Permute (Reordering dimensions - common for image channels)
# Example: Image tensor [Height, Width, Channels] -> [Channels, Height, Width]
x_image = torch.rand(size=(224, 224, 3))
x_permuted = x_image.permute(2, 0, 1)
print(f"Permuted shape: {x_permuted.shape}")  # torch.Size([3, 224, 224])

In [ ]:
# tensor indexing / slicing
x = torch.arange(1, 10).reshape(1, 3, 3)
# Tensor shape: (1, 3, 3)
# [[[1, 2, 3],
#   [4, 5, 6],
#   [7, 8, 9]]]

print(f"First element [0]:\n{x[0]}")
print(f"First row of matrix [0, 0]:\n{x[0, 0]}")
print(f"Specific element [0, 1, 2]: {x[0, 1, 2]}")  # Output: 6

# Use `:` to select all elements of a target dimension
print(f"All values of 0th dimension and 0th row, all columns:\n{x[:, 0, :]}")
print(f"Get all values of column index 1 across all rows:\n{x[:, :, 1]}")

In [ ]:
# NumPy Array to PyTorch Tensor
array = np.arange(1.0, 8.0)
tensor_from_np = torch.from_numpy(array)
print(f"NumPy Dtype: {array.dtype}")  # float64
print(f"Tensor Dtype: {tensor_from_np.dtype}")  # torch.float64

# Tensor to NumPy Array
tensor = torch.ones(7)
numpy_from_tensor = tensor.numpy()
print(f"Converted Array Dtype: {numpy_from_tensor.dtype}")  # float32

In [50]:
# random seeds
# Non-reproducible random tensors
rand_A = torch.rand(2, 2)
rand_B = torch.rand(2, 2)
print(f"Are A and B equal? {torch.equal(rand_A, rand_B)}")  # False

# Reproducible random tensors
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
rand_C = torch.rand(2, 2)

torch.manual_seed(RANDOM_SEED)
rand_D = torch.rand(2, 2)

print(f"Are C and D equal with seed? {torch.equal(rand_C, rand_D)}")  # True

In [51]:
# device agnostic code
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

# Count available GPUs (if CUDA available)
if torch.cuda.is_available():
    print(f"Device Count: {torch.cuda.device_count()}")
    print(f"Device Name: {torch.cuda.get_device_name(0)}")

# Moving Tensors between CPU and GPU
tensor_cpu = torch.tensor([1, 2, 3])
print(f"Tensor device before: {tensor_cpu.device}")

# Move tensor to target device
tensor_on_device = tensor_cpu.to(device)
print(f"Tensor device after: {tensor_on_device.device}")

# Note: NumPy does not support GPU tensors.
# To convert back to NumPy, move the tensor to CPU first:
tensor_back_to_cpu = tensor_on_device.cpu().numpy()